### ISSUE TITLE
Year counter missing

### ISSUE THREAD

**Issue by dasdan** [baden03/t-minus-countdown#5]
Hi, noticed that once an event date is passed, the counter starts counting up. Nice, but the elements are limited to weeks, days, h, m, s. I'm missing a year element to allow for counting the number of years an event already passed.

**Comment by baden03** [comment]
Years and months are not currently supported. However this is starting to be requested (this being the second time) - so we'll look into expanding this in our next release. Watch this space for updates.

**Comment by baden03** [comment]
Years and months have been added to version 2.4.0, just uploaded here on GitHub.
