### ISSUE TITLE
Wrong hours (+1)

### ISSUE THREAD

**Issue by zerx** [baden03/t-minus-countdown#6]
Current time: 14:51
I set the date and time to 14:59:00, and the counter value is: 01:07:59.
That's an hour more.

When you wait until the time is less than 1 hour, open the page with countdown and the seconds digit will be freeze.

**Comment by baden03** [comment]
two possibilities:
First, check your WordPress timezone settings to make sure that the system time matches your local time.

Second, check if you are using a caching plugin, as caching is a snapshot of the page at a specific time, and not created anew each time it's being requested..

**Comment by zerx** [comment]
- I checked the time, server is ok (CET), wp is ok (UTC+1)
- I don't use cache plugin.

**Comment by zerx** [comment]
Update:
I tested another website (other server). The result is the same as before.

**Comment by baden03** [comment]
Can you provide a link to either of the examples?

**Comment by zerx** [comment]
Yes of course. I created a test post with 2019-11-02 23:00:00:
http://gvm.kube.hu/2018/12/19/hello-vilag/

**Comment by zerx** [comment]
This code is correct with local time and target date in source.
On frontend, the time is, but time is one hour more:

jQuery(document).ready(function($) {
--
  | $('#new-years-eve-dashboard').tminusCountDown({
  | targetDate: {
  | 'day': 	02,
  | 'month': 11,
  | 'year': 2019,
  | 'hour': 23,
  | 'min': 	00,
  | 'sec': 	00,
  | 'localtime': '11/2/2019 10:00:14'
  | },
  | style: 'jedi',
  | id: 'new-years-eve',
  | event_id: '',
  | launchtarget: 'countdown',
  | omitWeeks: 'false',
  | omitmonths: 'false',
  | omityears: 'false'});
  | });

**Comment by baden03** [comment]
are you using a shortcode or the T(-) Countdown block?

**Comment by zerx** [comment]
@baden03 I'm using a shortcode.

**Comment by baden03** [comment]
@zerx please share the exact code so we can test it as well.
Also, you might want to explicitly set the timezone using the _timezone_ attribute:
`[tminus t="2019-11-09 23:00:00" timezone="Europe/Berlin" /]`

If your wordpress timezone value is +1... this will not take into account daylight savings.. so you might want to set that to a proper PHP timezone value:
https://www.php.net/manual/en/timezones.php

**Comment by zerx** [comment]
@baden03 
Ok, now I modified the code to yours. The problem is still alive.
So now the shortcode on the page is:
```[tminus t="2019-11-09 23:00:00" timezone="Europe/Budapest" /]```

**Comment by baden03** [comment]
this is very strange... and the current time that is displayed under dashboard > settings > timezone is correct?

**Comment by zerx** [comment]
Yes, it's corret:
```Universal time (UTC) is 2019-11-06 14:54:46. Local time is 2019-11-06 15:54:46.```

I tired another site with under construction function (with countdown), it's works fine.

**Comment by baden03** [comment]
if you set the timezone attribute, the counter will not change with WordPress... try removing the timezone attribute and then you can dial it in by changing the WP settings.

You might try turning off all plugins and seeing if you can find one that affects the timezone by turning them back on one-by-one...

Regardless, we'll get it figured out and resolved with you.

**Comment by zerx** [comment]
@baden03 

- turned off all plugins
- remove the attribute and change wp settings (it had never worked before)
- deactivate/active and remove/install this plugin
- hard flush my browser cache

It is very interesting that the counter does not change when I changed Wp time settings.
It wouldn't be a problem if I set the extension 1 hour earlier. However, in this case, the seconds counter will stop when it is within an hour.

**Comment by zerx** [comment]
@baden03 

I found another plugin with +1 hour effect:  Countdown Wpdevart
I have good counters (plugin, under constraction page in theme), but this plugin could help for us, cause They may have worked from the same source.

The time is central europe with winter time from october last sundary in Hungary. I think it will be the source of problem. I can't think of anything else.

**Comment by baden03** [comment]
Working on resolving this issue today... stand by for an update.

**Comment by baden03** [comment]
Version 2.4.6d has just been pushed to the repo and it should resolve the timezone issue.

**Comment by baden03** [comment]
Issue marked as resolved.

**Comment by zerx** [comment]
I tested at now.

- 2020
Widget: works fine, but number of seconds (and years,months,weeks display as sum of days ) not appear. So it's another problem.
Shortcode: does not work, [tminus t="2020-01-31 13:00:00" timezone="Europe/Budapest" /] -> 00:00:00

**Comment by baden03** [comment]
Widget? There is no sidebar widget anymore. Are you referring to the Gutenberg Block?
There is no timezone attribute, please remove this, only the timezone set in the WordPress Settings > General > Timezone is used. What is the exact value (and date/time) set under the WP Timezone settings?

We have tested this across a number of setups and have not seen an issue, so if you are continuing to experience the wrong time settings, please verify:
1. Your timezone is set correct
2. T(-) Countdown updated to the latest version
3. Browser Cache is cleared and the page is loading fresh

**Comment by zerx** [comment]
Yes I refering to the Gutenberg Block. I installed a fresh new site with this plugin, I thought it would be the best. Now its ok. The sorthcode is works fine at now. This issue resolved.

**Comment by baden03** [comment]
Very happy to hear that! Thank you for the feedback, and patience while we solved this.
