### ISSUE TITLE
hyperlink needs updating ;)

### ISSUE THREAD

**Issue by CrowdedTent** [baden03/t-minus-countdown#8]
Hey there Baden, 
could you possibly update the "Detailed documentation" link in the plugin's settings, in the "About" area?
Right now links to a "Page not found" page and it should link to:
https://plugins.twinpictures.de/plugins/t-minus-countdown/documentation/

Thanks for a cool plugin!
- Anastasios

**Comment by baden03** [comment]
The planned re-launch of the plugin oven has taken longer than planned (as always)
The links will revert back in the next update. Thank you for the feedback.

**Comment by CrowdedTent** [comment]
Good to know; feel free to ping me in case you'd fancy some collaboration on the website. Take care and stay safe.
